"""rollers URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/4.1/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""
from django.contrib import admin
from django.urls import path
from ordering import views
from rollers import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('slist/', views.show),
    path('listreport/', views.listreport),
    path('stateadd/',views.stateadd),
    path('statesave/',views.statesave),
    path('statedelete/<int:id>/',views.statedel),
    path('stateupdate/<int:id>/',views.stateupdate),
    path('stateedit/<int:id>/',views.stateedit),
    path('ulist/', views.unitlist),
    path('alist/',views.arealist),
    path('areaadd/',views.areaadd),
    path('areasave/',views.areasave),
    path('areadelete/<int:id>/',views.areatdel),
    path('areaedit/<int:id>/',views.areaedit),
    path('areaupdate/<int:id>/',views.areaupdate),
    path('unitadd/',views.unitadd),
    path('unitsave/',views.unitsave),
    path('areadelete/<int:id>/',views.areatdel),
    path('unitdelete/<int:id>/',views.unitdel),
    path('unitedit/<int:id>/',views.unitedit),
    path('unitupdate/<int:id>/',views.unitupdate),
    path('citylist/',views.citylist),
    path('cityadd/',views.cityadd),
    path('citysave/',views.citysave),
    path('citydelete/<int:id>/',views.citytdel),
    path('cityedit/<int:id>/',views.cityedit),
    path('cityupdate/<int:id>/',views.cityupdate),
    path('adminlist/',views.adminlist),
    path('adminadd/',views.adminadd),
    path('adminsave/',views.adminsave),
    path('admindelete/<int:id>/',views.admindel),
    path('adminedit/<int:id>/',views.adminedit),
    path('adminupdate/<int:id>/',views.adminupdate),
    path('employeelist/',views.employeelist),
    path('employeereport/',views.employeereport),
    path('employeeadd/',views.employeeadd),
    path('employeesave/',views.employeesave),
    path('employeedelete/<int:id>/',views.employeedel),
    path('employeeedit/<int:id>/',views.employeeedit),
    path('employeeupdate/<int:id>/',views.employeeupdate),
    path('testunit/',views.unitshow),
    path('customerlist/',views.customerlist),
    path('customerreport/',views.customerreport),
    path('customeradd/',views.customeradd),
    path('customersave/',views.customersave),
    path('customerdelete/<int:id>/',views.customerdel),
    path('customeredit/<int:id>/',views.customeredit),
    path('customerupdate/<int:id>/',views.customerupdate),
    path('supplierlist/',views.supplierlist),
    path('supplierreport/',views.supplierreport),
    path('supplieradd/',views.supplieradd),
    path('suppliersave/',views.suppliersave),
    path('supplierdelete/<int:id>/',views.supplierdel),
    path('supplieredit/<int:id>/',views.supplieredit),
    path('supplierupdate/<int:id>/',views.supplierupdate),
    path('producttypelist/',views.producttypelist),
    path('producttypeadd/',views.producttypeadd),
    path('producttypesave/',views.producttypesave),
    path('producttypedelete/<int:id>/',views.producttypedel),
    path('producttypeedit/<int:id>/',views.producttypeedit),
    path('producttypeupdate/<int:id>/',views.producttypeupdate),
    path('materiallist/',views.materiallist),
    path('materialadd/',views.materialadd),
    path('materialsave/',views.materialsave),
    path('materialdelete/<int:id>/',views.materialdel),
    path('materialedit/<int:id>/',views.materialedit),
    path('materialupdate/<int:id>/',views.materialupdate),
    path('purchaseorderlistd/<int:id>',views.purchaseorderlistd),
    path('purchaseorderlist/',views.purchaseorderlist),
    path('purchaseorderadd/',views.purchaseorderadd),
    path('purchaseordersave/',views.purchaseordersave),
    path('purchaseorderdelete/<int:id>/',views.purchaseorderdel),
    path('purchaseorderedit/<int:id>/',views.purchaseorderedit),
    path('purchaseorderupdate/<int:id>/',views.purchaseorderupdate),
    path('salesorderlistd/<int:id>',views.salesorderlistd),
    path('salesorderlist/',views.salesorderlist),
    path('salesorderadd/',views.salesorderadd),
    path('salesordersave/',views.salesordersave),
    path('salesorderdelete/<int:id>/',views.salesorderdel),
    path('salesorderedit/<int:id>/',views.salesorderedit),
    path('salesorderupdate/<int:id>/',views.salesorderupdate),
    path('billinglist/',views.billinglist),
    path('billingadd/',views.billingadd),
    path('billingsave/',views.billingsave),
    path('billingdelete/<int:id>/',views.billingdel),
    path('billingedit/<int:id>/',views.billingedit),
    path('billingupdate/<int:id>/',views.billingupdate),
    path('productlist/',views.productlist),
    path('productadd/',views.productadd),
    path('productsave/',views.productsave),
    path('productdelete/<int:id>/',views.productdel),
    path('productedit/<int:id>/',views.productedit),
    path('productupdate/<int:id>/',views.productupdate),
    path('materialstocklist/',views.materialstocklist),
    path('materialstockreport/',views.materialstockreport),
    path('materialstockadd/',views.materialstockadd),
    path('materialstocksave/',views.materialstocksave),
    path('materialstockdelete/<int:id>/',views.materialstockdel),
    path('materialstockedit/<int:id>/',views.materialstockedit),
    path('materialstockupdate/<int:id>/',views.materialstockupdate),
    path('paymentlist/',views.paymentlist),
    path('paymentadd/',views.paymentadd),
    path('paymentsave/',views.paymentsave),
    path('paymentdelete/<int:id>/',views.paymentdel),
    path('paymentedit/<int:id>/',views.paymentedit),
    path('paymentupdate/<int:id>/',views.paymentupdate),
    path('receiptlist/',views.receiptlist),
    path('receiptadd/',views.receiptadd),
    path('receiptsave/',views.receiptsave),
    path('receiptdelete/<int:id>/',views.receiptdel),
    path('receiptedit/<int:id>/',views.receiptedit),
    path('receiptupdate/<int:id>/',views.receiptupdate),
    path('readyproductlist/',views.readyproductlist),
    path('readyproductadd/',views.readyproductadd),
    path('readyproductsave/',views.readyproductsave),
    path('readyproductdelete/<int:id>/',views.readyproductdel),
    path('readyproductedit/<int:id>/',views.readyproductedit),
    path('readyproductupdate/<int:id>/',views.readyproductupdate),
    path('purchaseorderdetaillist/',views.purchaseorderdetaillist),
    path('purchaseorderdetailadd/',views.purchaseorderdetailadd),
    path('purchaseorderdetailsave/',views.purchaseorderdetailsave),
    path('purchaseorderdetaildelete/<int:id>/',views.purchaseorderdetaildel),
    path('purchaseorderdetailedit/<int:id>/',views.purchaseorderdetailedit),
    path('purchaseorderdetailupdate/<int:id>/',views.purchaseorderdetailupdate),
    path('billingdetaillist/',views.billingdetaillist),
    path('billingdetailadd/',views.billingdetailadd),
    path('billingdetailsave/',views.billingdetailsave),
    path('billingdetaildelete/<int:id>/',views.billingdetaildel),
    path('billingdetailedit/<int:id>/',views.billingdetailedit),
    path('billingdetailupdate/<int:id>/',views.billingdetailupdate),
    path('salesorderdetaillist/',views.salesorderdetaillist),
    path('salesorderdetailadd/',views.salesorderdetailadd),
    path('salesorderdetailsave/',views.salesorderdetailsave),
    path('salesorderdetaildelete/<int:id>/',views.salesorderdetaildel),
    path('salesorderdetailedit/<int:id>/',views.salesorderdetailedit),
    path('salesorderdetailupdate/<int:id>/',views.salesorderdetailupdate),
    path('login/',views.login),
    path('profile/',views.profile),
    path('myordersd/<int:id>/',views.myordersd),
    path('myorders/',views.myorders),
    path('updateprofile/',views.updateprofile),
    path('visitorhome/',views.visitor),
    path('productdetail/<int:id>/',views.productdetail),
    path('addtocart/',views.addtocart),
    path('registration/',views.registration),
    path('clogin/',views.clogin),
    path('contactus/',views.contactus),
    path('showcart/',views.showcart),
    path('deletecart/<int:id>/',views.deletecart),
    path('checkout/',views.checkout),
    path('aboutus/',views.aboutus),
    

]+static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)
